" --- THIS CODE IS AUTOMATICALLY GENERATED FROM BBAP ---

TYPES: BEGIN OF TESTTYPE,
	FIELD1TYPE I,
	FIELD2TYPE I,
END OF TESTTYPE.

DATA:	TESTENUMVALUE1_ TYPE STRING
	TESTENUMVALUE2_ TYPE STRING
	TESTENUMVALUE3_ TYPE STRING
	TEXTTEST_ TYPE TEXT
	VBAKTABLE_ TYPE STANDARD TABLE OF VBAK
	TESTVAR_ TYPE TESTTYPE
	TESTTABLE_ TYPE STANDARD TABLE OF TESTTYPE
	TESTTABLE2_ TYPE STANDARD TABLE OF TESTTYPE
	TESTNUMBER123_ TYPE I
	HELLO_ TYPE STRING
	WORLD_ TYPE STRING
	TESTCHAR_ TYPE C LENGTH 10
	CHARTEST2_ TYPE C LENGTH 20
	HELLOWORLD_ TYPE STRING
	NUM_ TYPE I
	NUM2_ TYPE I
	INTERNAL_HLFNY TYPE I
	TEST_ TYPE STRING
	NEGATIVENUM_ TYPE I
	TEST2_ TYPE ABAP_BOOL
	NOTEXPRESSION_ TYPE ABAP_BOOL
	ASGVSADF_ TYPE STRING
	SDFGUBI_ TYPE ABAP_BOOL
	LKNKSDXFV_ TYPE ABAP_BOOL
	INTERNAL_EGETK TYPE STRING
	INTERNAL_NWUWS TYPE STRING
	INTERNAL_BEGOV TYPE STRING
	I_I TYPE I
	TEST2_I TYPE STRING
	INTERNAL_EGLDL TYPE STRING
	INTERNAL_KYQJX TYPE STRING
	INTERNAL_GXNFR TYPE STRING
	RETURNONE_ TYPE L
	RETURNTWO_ TYPE I
	INTERNAL_RVZLT TYPE I
	DECLARERETURNONE_ TYPE L
	DECLARERETURNTWO_ TYPE I
	INTERNAL_VWRKW TYPE I
	SELECTED_VBELN_ TYPE STANDARD TABLE OF VBELN_VA
.


TESTENUMVALUE1_ = 'One'.
TESTENUMVALUE2_ = 'Two'.
TESTENUMVALUE3_ = 'Three'.
ALIASES TEXT FOR TYPE STRING.
TEXTTEST_ = 'Hello World!'.

FORM TESTTYPE_TESTFUNC
	USING THIS_D TYPE TESTTYPE .

	INTERNAL_SEHUR = THIS_D-FIELD1.
	WRITE INTERNAL_SEHUR.
	NEW-LINE.
ENDFORM.


FORM TESTTYPE_STATICTESTFUNC.

	INTERNAL_IAJAN = 'Static test'.
	WRITE INTERNAL_IAJAN.
	NEW-LINE.
ENDFORM.

PERFORM TESTTYPE_STATICTESTFUNC
.
TESTVAR_-FIELD1 = 1.
TESTVAR_-FIELD2 = 2.
SELECT TESTTABLE_-FIELD1, TESTTABLE_-FIELD2
	FROM TESTTABLE
	WHERE TESTTABLE_-FIELD1 EQ @TESTVAR_-FIELD1
	ORDER BY TESTTABLE_-FIELD1 
	UP TO 10 ROWS
	INTO TESTTABLE2_.
TESTNUMBER123_ = TESTVAR_-FIELD2.
HELLO_ = 'Hello '.
WORLD_ = 'World!'.
TESTCHAR_ = WORLD_.
CHARTEST2_ = 'Hello World!'.
CONCATENATE HELLO_ WORLD_ INTO HELLOWORLD_.
NUM_ = 255.
NUM2_ = 181.
INTERNAL_HLFNY = (NUM_ * 5).
CONCATENATE HELLOWORLD_ INTERNAL_HLFNY INTO TEST_.
NEGATIVENUM_ = (0 - NUM_).

IF (NUM_ EQ 0).
	INTERNAL_YKSSL = ABAP_TRUE.
ELSE.
	INTERNAL_YKSSL = ABAP_FALSE.
ENDIF.

TEST2_ = INTERNAL_YKSSL.

IF NOT (TEST2_ EQ ABAP_TRUE).
	INTERNAL_JPGXI = ABAP_TRUE.
ELSE.
	INTERNAL_JPGXI = ABAP_FALSE.
ENDIF.

NOTEXPRESSION_ = INTERNAL_JPGXI.
ASGVSADF_ = 'Hello'.

IF (HELLOWORLD_ EQ NUM2_).
	INTERNAL_SBYXU = ABAP_TRUE.
ELSE.
	INTERNAL_SBYXU = ABAP_FALSE.
ENDIF.


IF (INTERNAL_SBYXU AND ABAP_TRUE).
	INTERNAL_FTYRH = ABAP_TRUE.
ELSE.
	INTERNAL_FTYRH = ABAP_FALSE.
ENDIF.

SDFGUBI_ = INTERNAL_FTYRH.
LKNKSDXFV_ = SDFGUBI_.

IF (SDFGUBI_ EQ ABAP_TRUE).
	INTERNAL_EGETK = 'Is True!'.
	WRITE INTERNAL_EGETK.
	NEW-LINE.
ENDIF.


IF (NUM_ LT 100).
	INTERNAL_NWUWS = 'Is True!'.
	WRITE INTERNAL_NWUWS.
	NEW-LINE.
ENDIF.


WHILE (SDFGUBI_ EQ ABAP_TRUE).
	INTERNAL_BEGOV = 'Is True!'.
	WRITE INTERNAL_BEGOV.
	NEW-LINE.
ENDWHILE.

I_I = 0.

WHILE (I_I LT 20).
	TEST2_I = 'test'.
	INTERNAL_EGLDL = 'Hello Word 2!'.
	WRITE INTERNAL_EGLDL.
	NEW-LINE.
	I_I += 1.
ENDWHILE.


WHILE (NUM_ LT 10).
	INTERNAL_KYQJX = 'While loop!'.
	WRITE INTERNAL_KYQJX.
	NEW-LINE.
ENDWHILE.


IF (NUM_ LT 1).
	INTERNAL_GXNFR = 'Hello Word 1!'.
	WRITE INTERNAL_GXNFR.
	NEW-LINE.
ELSEIF (NUM_ GT 5).
	INTERNAL_FDOHD = 'Hello Word 2!'.
	WRITE INTERNAL_FDOHD.
	NEW-LINE.
ELSE.
	INTERNAL_ISHWR = 'Hello Word 3!'.
	WRITE INTERNAL_ISHWR.
	NEW-LINE.
ENDIF.

INTERNAL_RVZLT = 5.
PERFORM TEST2
	USING INTERNAL_RVZLT 
	CHANGING RETURNONE_ RETURNTWO_ .
INTERNAL_VWRKW = 5.
PERFORM TEST2
	USING INTERNAL_VWRKW 
	CHANGING DECLARERETURNONE_ DECLARERETURNTWO_ .

FORM TEST
	USING PARAM1_ TYPE I 
	CHANGING INTERNAL_MOODY TYPE I .

	INTERNAL_MOODY = 1.
ENDFORM.


FORM TEST2
	USING PARAM1_B TYPE I 
	CHANGING INTERNAL_JPBYT TYPE L INTERNAL_QZYFT TYPE I .

	HI_B = 'Hi!'.
	INTERNAL_JPBYT = 1.
	INTERNAL_QZYFT = 0.
ENDFORM.

SELECT VBAK-VBELN
	FROM VBAK
	WHERE VBAK-VBELN EQ '123'
	INTO SELECTED_VBELN_.
