" --- THIS CODE IS AUTOMATICALLY GENERATED FROM BBAP ---

TYPES: BEGIN OF TESTTYPE,
	FIELD1TYPE I,
	FIELD2TYPE I,
END OF TESTTYPE.

DATA:	TESTENUMVALUE1_ TYPE STRING
	TESTENUMVALUE2_ TYPE STRING
	TESTENUMVALUE3_ TYPE STRING
	TEXTTEST_ TYPE TEXT
	VBAKTABLE_ TYPE STANDARD TABLE OF VBAK
	TESTVAR_ TYPE TESTTYPE
	TESTTABLE_ TYPE STANDARD TABLE OF TESTTYPE
	TESTTABLE2_ TYPE STANDARD TABLE OF TESTTYPE
	TESTNUMBER123_ TYPE I
	HELLO_ TYPE STRING
	WORLD_ TYPE STRING
	TESTCHAR_ TYPE C LENGTH 10
	CHARTEST2_ TYPE C LENGTH 20
	HELLOWORLD_ TYPE STRING
	NUM_ TYPE I
	NUM2_ TYPE I
	INTERNAL_LRLFN TYPE I
	TEST_ TYPE STRING
	NEGATIVENUM_ TYPE I
	TEST2_ TYPE ABAP_BOOL
	NOTEXPRESSION_ TYPE ABAP_BOOL
	ASGVSADF_ TYPE STRING
	SDFGUBI_ TYPE ABAP_BOOL
	LKNKSDXFV_ TYPE ABAP_BOOL
	INTERNAL_NZQBY TYPE STRING
	INTERNAL_HPHHE TYPE STRING
	INTERNAL_IIPLB TYPE STRING
	I_I TYPE I
	TEST2_I TYPE STRING
	INTERNAL_LHAZJ TYPE STRING
	INTERNAL_JZBKZ TYPE STRING
	INTERNAL_SEIQH TYPE STRING
	RETURNONE_ TYPE L
	RETURNTWO_ TYPE I
	INTERNAL_AXLSJ TYPE I
	DECLARERETURNONE_ TYPE L
	DECLARERETURNTWO_ TYPE I
	INTERNAL_KJYWM TYPE I
	SELECTED_VBELN_ TYPE STANDARD TABLE OF VBELN_VA
.


TESTENUMVALUE1_ = 'One'.
TESTENUMVALUE2_ = 'Two'.
TESTENUMVALUE3_ = 'Three'.
ALIASES TEXT FOR TYPE STRING.
TEXTTEST_ = 'Hello World!'.

FORM TESTTYPE_TESTFUNC
	USING THIS_D TYPE TESTTYPE .

	INTERNAL_XBWNB = THIS_D-FIELD1.
	WRITE INTERNAL_XBWNB.
	NEW-LINE.
ENDFORM.


FORM TESTTYPE_STATICTESTFUNC.

	INTERNAL_DPBOS = 'Static test'.
	WRITE INTERNAL_DPBOS.
	NEW-LINE.
ENDFORM.

PERFORM TESTTYPE_STATICTESTFUNC
.
TESTVAR_-FIELD1 = 1.
TESTVAR_-FIELD2 = 2.
SELECT TESTTABLE_-FIELD1, TESTTABLE_-FIELD2
	FROM TESTTABLE
	WHERE TESTTABLE_-FIELD1 EQ @TESTVAR_-FIELD1
	ORDER BY TESTTABLE_-FIELD1 
	UP TO 10 ROWS
	INTO TESTTABLE2_.
TESTNUMBER123_ = TESTVAR_-FIELD2.
HELLO_ = 'Hello '.
WORLD_ = 'World!'.
TESTCHAR_ = WORLD_.
CHARTEST2_ = 'Hello World!'.
CONCATENATE HELLO_ WORLD_ INTO HELLOWORLD_.
NUM_ = 255.
NUM2_ = 181.
INTERNAL_LRLFN = (NUM_ * 5).
CONCATENATE HELLOWORLD_ INTERNAL_LRLFN INTO TEST_.
NEGATIVENUM_ = (0 - NUM_).

IF (NUM_ EQ 0).
	INTERNAL_SXFPJ = ABAP_TRUE.
ELSE.
	INTERNAL_SXFPJ = ABAP_FALSE.
ENDIF.

TEST2_ = INTERNAL_SXFPJ.

IF NOT (TEST2_ EQ ABAP_TRUE).
	INTERNAL_KWMHQ = ABAP_TRUE.
ELSE.
	INTERNAL_KWMHQ = ABAP_FALSE.
ENDIF.

NOTEXPRESSION_ = INTERNAL_KWMHQ.
ASGVSADF_ = 'Hello'.

IF (HELLOWORLD_ EQ NUM2_).
	INTERNAL_AGLGX = ABAP_TRUE.
ELSE.
	INTERNAL_AGLGX = ABAP_FALSE.
ENDIF.


IF (INTERNAL_AGLGX AND ABAP_TRUE).
	INTERNAL_UUDIQ = ABAP_TRUE.
ELSE.
	INTERNAL_UUDIQ = ABAP_FALSE.
ENDIF.

SDFGUBI_ = INTERNAL_UUDIQ.
LKNKSDXFV_ = SDFGUBI_.

IF (SDFGUBI_ EQ ABAP_TRUE).
	INTERNAL_NZQBY = 'Is True!'.
	WRITE INTERNAL_NZQBY.
	NEW-LINE.
ENDIF.


IF (NUM_ LT 100).
	INTERNAL_HPHHE = 'Is True!'.
	WRITE INTERNAL_HPHHE.
	NEW-LINE.
ENDIF.


WHILE (SDFGUBI_ EQ ABAP_TRUE).
	INTERNAL_IIPLB = 'Is True!'.
	WRITE INTERNAL_IIPLB.
	NEW-LINE.
ENDWHILE.

I_I = 0.

WHILE (I_I LT 20).
	TEST2_I = 'test'.
	INTERNAL_LHAZJ = 'Hello Word 2!'.
	WRITE INTERNAL_LHAZJ.
	NEW-LINE.
	I_I += 1.
ENDWHILE.


WHILE (NUM_ LT 10).
	INTERNAL_JZBKZ = 'While loop!'.
	WRITE INTERNAL_JZBKZ.
	NEW-LINE.
ENDWHILE.


IF (NUM_ LT 1).
	INTERNAL_SEIQH = 'Hello Word 1!'.
	WRITE INTERNAL_SEIQH.
	NEW-LINE.
ELSEIF (NUM_ GT 5).
	INTERNAL_SNGYB = 'Hello Word 2!'.
	WRITE INTERNAL_SNGYB.
	NEW-LINE.
ELSE.
	INTERNAL_RXWAT = 'Hello Word 3!'.
	WRITE INTERNAL_RXWAT.
	NEW-LINE.
ENDIF.

INTERNAL_AXLSJ = 5.
PERFORM TEST2
	USING INTERNAL_AXLSJ 
	CHANGING RETURNONE_ RETURNTWO_ .
INTERNAL_KJYWM = 5.
PERFORM TEST2
	USING INTERNAL_KJYWM 
	CHANGING DECLARERETURNONE_ DECLARERETURNTWO_ .

FORM TEST
	USING PARAM1_ TYPE I 
	CHANGING INTERNAL_QGDXD TYPE I .

	INTERNAL_QGDXD = 1.
ENDFORM.


FORM TEST2
	USING PARAM1_B TYPE I 
	CHANGING INTERNAL_FDXNJ TYPE L INTERNAL_EQMYA TYPE I .

	HI_B = 'Hi!'.
	INTERNAL_FDXNJ = 1.
	INTERNAL_EQMYA = 0.
ENDFORM.

SELECT VBAK-VBELN
	FROM VBAK
	WHERE VBAK-VBELN EQ '123'
	INTO SELECTED_VBELN_.
